export enum UserCategoryService {
  TI = "T.I",
  CFTV = "CFTV",
  INETRFONIA = "INETRFONIA",
  CONTROLE_DE_ACESSO = "CONTROLE DE ACESSO",
  AUTOMACAO_RESIDENCIAL = "AUTOMACAO RESIDENCIAL",
  ANTENA_COLETIVA = "ANTENA COLETIVA",
}
